/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Banco.View;

import Banco.Model.Cliente;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author Erick Alessi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public int getSelectedLine(MouseEvent evt) {
        return this.getClienteViewTable().rowAtPoint(evt.getPoint());
    }

    public void showError(String message) {
        JOptionPane.showMessageDialog(null, message, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pesquisarClienteField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clienteAtualizarButton = new javax.swing.JButton();
        clienteNovoButton = new javax.swing.JButton();
        clienteDeletarButton = new javax.swing.JButton();
        clienteCpfField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clienteRgField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clienteNomeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clienteSobreNomeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clienteSalarioField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clienteEnderecoField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        clienteListarButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        clienteViewTable = new javax.swing.JTable();
        clienteOrdenarPorCombo = new javax.swing.JComboBox<>();
        limpaClienteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cpfFieldNovaConta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        clienteEncontradoNovaConta = new javax.swing.JTextField();
        buscarCPFButtonNovaConta = new javax.swing.JButton();
        tipoContaComboBoxeNovaConta = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        contaCorrenteJPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        limiteCCField = new javax.swing.JTextField();
        depositoInicialCCField = new javax.swing.JTextField();
        contaInvestimentoJPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        depositoMinimoCIField = new javax.swing.JTextField();
        montanteMinimoCIField = new javax.swing.JTextField();
        depositoInicialCIField = new javax.swing.JTextField();
        criarContaButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        numeroDaContaField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        numeroContaOCField = new javax.swing.JTextField();
        buscarContaOCButton = new javax.swing.JButton();
        clienteOCField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        saldoOCField = new javax.swing.JTextField();
        valorOCField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        sacarOCButton = new javax.swing.JButton();
        depositarOCButton = new javax.swing.JButton();
        renumeraOCButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANCO BANCO S.A.");

        pesquisarClienteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarClienteFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisa");

        jLabel3.setText("Ordenar");

        clienteAtualizarButton.setLabel("ATUALIZAR");
        clienteAtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteAtualizarButtonActionPerformed(evt);
            }
        });

        clienteNovoButton.setLabel("NOVO");
        clienteNovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteNovoButtonActionPerformed(evt);
            }
        });

        clienteDeletarButton.setText("DELETAR");

        clienteCpfField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCpfFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        clienteRgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteRgFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("RG");

        clienteNomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteNomeFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("NOME");

        clienteSobreNomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteSobreNomeFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("SOBRENOME");

        clienteSalarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteSalarioFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("SALARIO");

        clienteEnderecoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEnderecoFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("ENDEREÇO");

        clienteListarButton.setLabel("LISTAR");
        clienteListarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteListarButtonActionPerformed(evt);
            }
        });

        scrollPanel.setViewportView(clienteViewTable);

        clienteOrdenarPorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "SobreNome", "Salário" }));
        clienteOrdenarPorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteOrdenarPorComboActionPerformed(evt);
            }
        });

        limpaClienteButton.setText("LIMPA CLIENTE");
        limpaClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaClienteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPanel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisarClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clienteOrdenarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clienteListarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel6)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(clienteCpfField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clienteRgField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clienteNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(clienteSobreNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(clienteSalarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(clienteEnderecoField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(86, 86, 86))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(353, Short.MAX_VALUE)
                        .addComponent(clienteAtualizarButton)
                        .addGap(18, 18, 18)
                        .addComponent(clienteDeletarButton)
                        .addGap(196, 196, 196))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(limpaClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clienteNovoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(clienteListarButton)
                    .addComponent(clienteOrdenarPorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteAtualizarButton)
                    .addComponent(clienteDeletarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteEnderecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteSalarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteSobreNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteRgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteCpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteNovoButton)
                    .addComponent(limpaClienteButton))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pesquisarClienteField.getAccessibleContext().setAccessibleName("pesquisaCampo");
        pesquisarClienteField.getAccessibleContext().setAccessibleDescription("");
        clienteNovoButton.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Clientes", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        cpfFieldNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFieldNovaContaActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF CLIENTE");

        clienteEncontradoNovaConta.setEditable(false);
        clienteEncontradoNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEncontradoNovaContaActionPerformed(evt);
            }
        });

        buscarCPFButtonNovaConta.setText("BUSCAR");

        tipoContaComboBoxeNovaConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente", "Conta Investimento" }));
        tipoContaComboBoxeNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoContaComboBoxeNovaContaActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo de Conta");

        jLabel11.setText("CONTA CORRENTE");

        jLabel13.setText("DEPOSITO INICIAL");

        jLabel14.setText("LIMITE");

        javax.swing.GroupLayout contaCorrenteJPanelLayout = new javax.swing.GroupLayout(contaCorrenteJPanel);
        contaCorrenteJPanel.setLayout(contaCorrenteJPanelLayout);
        contaCorrenteJPanelLayout.setHorizontalGroup(
            contaCorrenteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaCorrenteJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contaCorrenteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contaCorrenteJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(depositoInicialCCField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contaCorrenteJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limiteCCField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(contaCorrenteJPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contaCorrenteJPanelLayout.setVerticalGroup(
            contaCorrenteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaCorrenteJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contaCorrenteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(depositoInicialCCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contaCorrenteJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(limiteCCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jLabel12.setText("CONTA INVESTIMENTO");

        jLabel16.setText("MONTANTE MINIMO");

        jLabel17.setText("DEPOSITO MINIMO");

        jLabel18.setText("DEPOSITO INICIAL");

        montanteMinimoCIField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montanteMinimoCIFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contaInvestimentoJPanelLayout = new javax.swing.GroupLayout(contaInvestimentoJPanel);
        contaInvestimentoJPanel.setLayout(contaInvestimentoJPanelLayout);
        contaInvestimentoJPanelLayout.setHorizontalGroup(
            contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaInvestimentoJPanelLayout.createSequentialGroup()
                .addGroup(contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contaInvestimentoJPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel12))
                    .addGroup(contaInvestimentoJPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contaInvestimentoJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(montanteMinimoCIField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contaInvestimentoJPanelLayout.createSequentialGroup()
                                .addGroup(contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(32, 32, 32)
                                .addGroup(contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depositoMinimoCIField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(depositoInicialCIField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        contaInvestimentoJPanelLayout.setVerticalGroup(
            contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaInvestimentoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(montanteMinimoCIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(depositoMinimoCIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contaInvestimentoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(depositoInicialCIField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        criarContaButton.setText("CRIAR CONTA");

        jLabel15.setText("NUMERO DA CONTA");

        numeroDaContaField.setEditable(false);
        numeroDaContaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDaContaFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteEncontradoNovaConta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cpfFieldNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarCPFButtonNovaConta)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(tipoContaComboBoxeNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(contaCorrenteJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contaInvestimentoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97)))
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(numeroDaContaField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(criarContaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfFieldNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buscarCPFButtonNovaConta)
                    .addComponent(tipoContaComboBoxeNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteEncontradoNovaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(numeroDaContaField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarContaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contaCorrenteJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contaInvestimentoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nova Conta", jPanel2);

        jLabel19.setText("Nº DA CONTA");

        numeroContaOCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroContaOCFieldActionPerformed(evt);
            }
        });

        buscarContaOCButton.setText("BUSCAR");

        clienteOCField.setEditable(false);
        clienteOCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteOCFieldActionPerformed(evt);
            }
        });

        jLabel20.setText("CLIENTE");

        jLabel21.setText("SALDO");

        saldoOCField.setEditable(false);
        saldoOCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoOCFieldActionPerformed(evt);
            }
        });

        valorOCField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valorOCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorOCFieldActionPerformed(evt);
            }
        });

        jLabel22.setText("VALOR");

        sacarOCButton.setText("SACAR");

        depositarOCButton.setText("DEPOSITAR");
        depositarOCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarOCButtonActionPerformed(evt);
            }
        });

        renumeraOCButton.setText("REMUNERA");
        renumeraOCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renumeraOCButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(41, 41, 41)
                        .addComponent(numeroContaOCField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarContaOCButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(clienteOCField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saldoOCField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(sacarOCButton)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorOCField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(depositarOCButton)
                                .addGap(49, 49, 49)
                                .addComponent(renumeraOCButton)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroContaOCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(buscarContaOCButton)
                    .addComponent(clienteOCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(saldoOCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorOCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sacarOCButton)
                    .addComponent(depositarOCButton)
                    .addComponent(renumeraOCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Operações em Conta", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getClienteViewTable() {
        return clienteViewTable;
    }

    public void setClienteViewTable(JTable clienteViewTable) {
        this.clienteViewTable = clienteViewTable;
    }

    public int confirmDialog(String message) {
        JPanel panel = new JPanel();
        JLabel label1 = new JLabel(message);
        label1.setVerticalAlignment(SwingConstants.BOTTOM);
        label1.setBounds(20, 20, 200, 30);
        label1.setHorizontalAlignment(SwingConstants.CENTER);
        panel.add(label1);
        UIManager.put("OptionPane.minimumSize", new Dimension(400, 200));
        return JOptionPane.showConfirmDialog(null, panel, "Confirmação",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
    }

    public void setCliente(Cliente cliente) {
        //Seta os dados nos componentes
        clienteNomeField.setText(cliente.getNome());
        clienteSobreNomeField.setText(cliente.getSobrenome());
        clienteCpfField.setText(cliente.getCPF());
        clienteRgField.setText(Integer.toString(cliente.getRG()));
        clienteSalarioField.setText(Double.toString(cliente.getSalario()));
        clienteEnderecoField.setText(cliente.getEndereco());
    }


    private void clienteCpfFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCpfFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCpfFieldActionPerformed

    private void clienteRgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteRgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteRgFieldActionPerformed

    private void clienteNomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNomeFieldActionPerformed

    private void clienteSobreNomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteSobreNomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteSobreNomeFieldActionPerformed

    private void clienteSalarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteSalarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteSalarioFieldActionPerformed

    private void clienteEnderecoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEnderecoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEnderecoFieldActionPerformed

    private void clienteNovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNovoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNovoButtonActionPerformed

    private void clienteAtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteAtualizarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteAtualizarButtonActionPerformed

    private void clienteListarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteListarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteListarButtonActionPerformed

    private void numeroDaContaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDaContaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDaContaFieldActionPerformed

    private void tipoContaComboBoxeNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoContaComboBoxeNovaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoContaComboBoxeNovaContaActionPerformed

    private void cpfFieldNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFieldNovaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFieldNovaContaActionPerformed

    private void numeroContaOCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroContaOCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroContaOCFieldActionPerformed

    private void saldoOCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoOCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoOCFieldActionPerformed

    private void valorOCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorOCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorOCFieldActionPerformed

    private void depositarOCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarOCButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositarOCButtonActionPerformed

    private void renumeraOCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renumeraOCButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renumeraOCButtonActionPerformed

    private void pesquisarClienteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarClienteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarClienteFieldActionPerformed

    private void clienteOrdenarPorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteOrdenarPorComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteOrdenarPorComboActionPerformed

    private void limpaClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaClienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpaClienteButtonActionPerformed

   

    private void montanteMinimoCIFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montanteMinimoCIFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montanteMinimoCIFieldActionPerformed

    private void clienteEncontradoNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEncontradoNovaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteEncontradoNovaContaActionPerformed

    private void clienteOCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteOCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteOCFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCPFButtonNovaConta;
    private javax.swing.JButton buscarContaOCButton;
    private javax.swing.JButton clienteAtualizarButton;
    private javax.swing.JTextField clienteCpfField;
    private javax.swing.JButton clienteDeletarButton;
    private javax.swing.JTextField clienteEncontradoNovaConta;
    private javax.swing.JTextField clienteEnderecoField;
    private javax.swing.JButton clienteListarButton;
    private javax.swing.JTextField clienteNomeField;
    private javax.swing.JButton clienteNovoButton;
    private javax.swing.JTextField clienteOCField;
    private javax.swing.JComboBox<String> clienteOrdenarPorCombo;
    private javax.swing.JTextField clienteRgField;
    private javax.swing.JTextField clienteSalarioField;
    private javax.swing.JTextField clienteSobreNomeField;
    private javax.swing.JTable clienteViewTable;
    private javax.swing.JPanel contaCorrenteJPanel;
    private javax.swing.JPanel contaInvestimentoJPanel;
    private javax.swing.JTextField cpfFieldNovaConta;
    private javax.swing.JButton criarContaButton;
    private javax.swing.JButton depositarOCButton;
    private javax.swing.JTextField depositoInicialCCField;
    private javax.swing.JTextField depositoInicialCIField;
    private javax.swing.JTextField depositoMinimoCIField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField limiteCCField;
    private javax.swing.JButton limpaClienteButton;
    private javax.swing.JTextField montanteMinimoCIField;
    private javax.swing.JTextField numeroContaOCField;
    private javax.swing.JTextField numeroDaContaField;
    private javax.swing.JTextField pesquisarClienteField;
    private javax.swing.JButton renumeraOCButton;
    private javax.swing.JButton sacarOCButton;
    private javax.swing.JTextField saldoOCField;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JComboBox<String> tipoContaComboBoxeNovaConta;
    private javax.swing.JTextField valorOCField;
    // End of variables declaration//GEN-END:variables

    public JButton getClienteAtualizarButton() {
        return clienteAtualizarButton;
    }

    public void setClienteAtualizarButton(JButton clienteAtualizarButton) {
        this.clienteAtualizarButton = clienteAtualizarButton;
    }

    public JTextField getClienteCpfField() {
        return clienteCpfField;
    }

    public void setClienteCpfField(JTextField clienteCpfField) {
        this.clienteCpfField = clienteCpfField;
    }

    public JButton getClienteDeletarButton() {
        return clienteDeletarButton;
    }

    public void setClienteDeletarButton(JButton clienteDeletarButton) {
        this.clienteDeletarButton = clienteDeletarButton;
    }

    public JTextField getClienteEnderecoField() {
        return clienteEnderecoField;
    }

    public void setClienteEnderecoField(JTextField clienteEnderecoField) {
        this.clienteEnderecoField = clienteEnderecoField;
    }

    public JButton getClienteListarButton() {
        return clienteListarButton;
    }

    public void setClienteListarButton(JButton clienteListarButton) {
        this.clienteListarButton = clienteListarButton;
    }

    public JTextField getClienteNomeField() {
        return clienteNomeField;
    }

    public void setClienteNomeField(JTextField clienteNomeField) {
        this.clienteNomeField = clienteNomeField;
    }

    public JButton getClienteNovoButton() {
        return clienteNovoButton;
    }

    public void setClienteNovoButton(JButton clienteNovoButton) {
        this.clienteNovoButton = clienteNovoButton;
    }

    public JTextField getClienteRgField() {
        return clienteRgField;
    }

    public void setClienteRgField(JTextField clienteRgField) {
        this.clienteRgField = clienteRgField;
    }

    public JTextField getClienteSalarioField() {
        return clienteSalarioField;
    }

    public void setClienteSalarioField(JTextField clienteSalarioField) {
        this.clienteSalarioField = clienteSalarioField;
    }

    public JTextField getClienteSobreNomeField() {
        return clienteSobreNomeField;
    }

    public void setClienteSobreNomeField(JTextField clienteSobreNomeField) {
        this.clienteSobreNomeField = clienteSobreNomeField;
    }

    public JComboBox<String> getClienteOrdenarPorCombo() {
        return clienteOrdenarPorCombo;
    }

    public void setClienteOrdenarPorCombo(JComboBox<String> clienteOrdenarPorCombo) {
        this.clienteOrdenarPorCombo = clienteOrdenarPorCombo;
    }

    public JTextField getPesquisarClienteField() {
        return pesquisarClienteField;
    }

    public void setPesquisarClienteField(JTextField pesquisarClienteField) {
        this.pesquisarClienteField = pesquisarClienteField;
    }

    public Cliente getClienteFromFields() {
        return new Cliente(this.getClienteNomeField().getText(), this.getClienteSobreNomeField().getText(), Integer.valueOf(this.getClienteRgField().getText()), this.getClienteCpfField().getText(), this.getClienteEnderecoField().getText(), Double.valueOf(this.getClienteSalarioField().getText()));
    }
    
     public JButton getBuscarCPFButtonNovaConta() {
        return buscarCPFButtonNovaConta;
    }

    public void setBuscarCPFButtonNovaConta(JButton buscarCPFButtonNovaConta) {
        this.buscarCPFButtonNovaConta = buscarCPFButtonNovaConta;
    }

    public JPanel getContaCorrenteJPanel() {
        return contaCorrenteJPanel;
    }

    public void setContaCorrenteJPanel(JPanel contaCorrenteJPanel) {
        this.contaCorrenteJPanel = contaCorrenteJPanel;
    }

    public JTextField getCpfFieldNovaConta() {
        return cpfFieldNovaConta;
    }

    public void setCpfFieldNovaConta(JTextField cpfFieldNovaConta) {
        this.cpfFieldNovaConta = cpfFieldNovaConta;
    }

    public JButton getCriarContaButton() {
        return criarContaButton;
    }

    public void setCriarContaButton(JButton criarContaButton) {
        this.criarContaButton = criarContaButton;
    }

    public JTextField getDepositoInicialCCField() {
        return depositoInicialCCField;
    }

    public void setDepositoInicialCCField(JTextField depositoInicialCCField) {
        this.depositoInicialCCField = depositoInicialCCField;
    }

    public JTextField getDepositoInicialCIField() {
        return depositoInicialCIField;
    }

    public void setDepositoInicialCIField(JTextField depositoInicialCIField) {
        this.depositoInicialCIField = depositoInicialCIField;
    }

    public JTextField getDepositoMinimoCIField() {
        return depositoMinimoCIField;
    }

    public void setDepositoMinimoCIField(JTextField depositoMinimoCIField) {
        this.depositoMinimoCIField = depositoMinimoCIField;
    }

    public JTextField getLimiteCCField() {
        return limiteCCField;
    }

    public void setLimiteCCField(JTextField limiteCCField) {
        this.limiteCCField = limiteCCField;
    }

    public JButton getLimpaClienteButton() {
        return limpaClienteButton;
    }

    public void setLimpaClienteButton(JButton limpaClienteButton) {
        this.limpaClienteButton = limpaClienteButton;
    }

    public JTextField getMontanteMinimoCIField() {
        return montanteMinimoCIField;
    }

    public void setMontanteMinimoCIField(JTextField montanteMinimoCIField) {
        this.montanteMinimoCIField = montanteMinimoCIField;
    }

    public JTextField getNumeroDaContaField() {
        return numeroDaContaField;
    }

    public void setNumeroDaContaField(JTextField numeroDaContaField) {
        this.numeroDaContaField = numeroDaContaField;
    }

    public JScrollPane getScrollPanel() {
        return scrollPanel;
    }

    public void setScrollPanel(JScrollPane scrollPanel) {
        this.scrollPanel = scrollPanel;
    }

    public JComboBox<String> getTipoContaComboBoxeNovaConta() {
        return tipoContaComboBoxeNovaConta;
    }

    public void setTiipoContaComboBoxeNovaConta(JComboBox<String> tiipoContaComboBoxeNovaConta) {
        this.tipoContaComboBoxeNovaConta = tiipoContaComboBoxeNovaConta;
    }

    public JTextField getClienteEncontradoNovaConta() {
        return clienteEncontradoNovaConta;
    }

    public void setClienteEncontradoNovaConta(JTextField clienteEncontradoNovaConta) {
        this.clienteEncontradoNovaConta = clienteEncontradoNovaConta;
    }

    public JPanel getContaInvestimentoJPanel() {
        return contaInvestimentoJPanel;
    }

    public void setContaInvestimentoJPanel(JPanel contaInvestimentoJPanel) {
        this.contaInvestimentoJPanel = contaInvestimentoJPanel;
    }

    public JButton getBuscarContaOCButton() {
        return buscarContaOCButton;
    }

    public void setBuscarContaOCButton(JButton buscarContaOCButton) {
        this.buscarContaOCButton = buscarContaOCButton;
    }

    public JTextField getClienteOCField() {
        return clienteOCField;
    }

    public void setClienteOCField(JTextField clienteOCField) {
        this.clienteOCField = clienteOCField;
    }

    public JButton getDepositarOCButton() {
        return depositarOCButton;
    }

    public void setDepositarOCButton(JButton depositarOCButton) {
        this.depositarOCButton = depositarOCButton;
    }

    public JTextField getNumeroContaOCField() {
        return numeroContaOCField;
    }

    public void setNumeroContaOCField(JTextField numeroContaOCField) {
        this.numeroContaOCField = numeroContaOCField;
    }

    public JButton getRenumeraOCButton() {
        return renumeraOCButton;
    }

    public void setRenumeraOCButton(JButton renumeraOCButton) {
        this.renumeraOCButton = renumeraOCButton;
    }

    public JButton getSacarOCButton() {
        return sacarOCButton;
    }

    public void setSacarOCButton(JButton sacarOCButton) {
        this.sacarOCButton = sacarOCButton;
    }

    public JTextField getSaldoOCField() {
        return saldoOCField;
    }

    public void setSaldoOCField(JTextField saldoOCField) {
        this.saldoOCField = saldoOCField;
    }

    public JTextField getValorOCField() {
        return valorOCField;
    }

    public void setValorOCField(JTextField valorOCField) {
        this.valorOCField = valorOCField;
    }
    
    

}
